### PR TITLE
Fix links to courses.zurb.com and on templates.html

### PR DESCRIPTION
**Pull request by jonemo**
Addresses some of the dead links mentioned in https://github.com/foundation/foundation-marketing/issues/21

There are three remaining dead links on this page for which I cannot figure out what the correct link should be: 
* https://zurb.com/responsive
* https://get.foundation/sites/download.html
* https://get.foundation/sites/download.html

This is my first PR here and I don't really know my way around this repo or Foundation in general. Happy to address feedback or for someone else who has a better understanding of this repo to take over this PR.

### CODE REVIEW

**Comment by DanielRuf** [comment]
>     * get.foundation/sites/download.html

You can use https://download.get.foundation/sites/download/

**Comment by jonemo** [comment]
> You can use https://download.get.foundation/sites/download/

@DanielRuf I am going to leave the download links for another passerby to address. Reasons I hesitate:

* Because of the additional subdomain, the normal way of building links with `{{root}}` won't work. Maybe it's ok to replace that with a hard coded link? Or maybe something fancier is in order?
* I can't find an equivalent link for Email templates. Maybe [this page](https://get.foundation/emails/getting-started.html) is the closest to a download page there is for Foundation for Emails? If so, then maybe the navigation link to "Downloads" shouldn't exist?
* One of the occurrences is on `downloads-old.html`. Based on name and a quick search, I think this might no longer be in use and can be deleted?

**Comment by DanielRuf** [comment]
@jonemo you can use the links for the download that I have provided. We set up a new hosting just for the customizer.

**Comment by jonemo** [comment]
Just to make sure this doesn't get held up unnecessarily: I am not planning on pushing any additional commits to this PR. Feel free to merge.

**Pull request merged**
